package errdefs

const (
	CodeNotImplemented                   = "NOT_IMPLEMENTED"
	CodeOutputWriteFailed                = "OUTPUT_WRITE_FAILED"
	CodeUnknownCommand                   = "UNKNOWN_COMMAND"
	CodeUsage                            = "USAGE_ERROR"
	CodeAuthRequired                     = "AUTH_REQUIRED"
	CodeAuthInvalid                      = "AUTH_INVALID"
	CodeServerRequestFailed              = "SERVER_REQUEST_FAILED"
	CodeServerResponseInvalid            = "SERVER_RESPONSE_INVALID"
	CodeNetworkRequestFailed             = "NETWORK_REQUEST_FAILED"
	CodeUpdateRequired                   = "UPDATE_REQUIRED"
	CodeInitPathInvalid                  = "INIT_PATH_INVALID"
	CodeInitManifestInvalid              = "INIT_MANIFEST_INVALID"
	CodeInitFileChecksumMismatch         = "INIT_FILE_CHECKSUM_MISMATCH"
	CodeInitFileDownloadFailed           = "INIT_FILE_DOWNLOAD_FAILED"
	CodeUpdateDownloadFailed             = "UPDATE_DOWNLOAD_FAILED"
	CodeUpdateChecksumMismatch           = "UPDATE_CHECKSUM_MISMATCH"
	CodeUpdateReplaceFailed              = "UPDATE_REPLACE_FAILED"
	CodeUpdateUnsupportedInstallLocation = "UPDATE_UNSUPPORTED_INSTALL_LOCATION"
	CodeUpdateHelperMissing              = "UPDATE_HELPER_MISSING"
	CodeUpdateHelperFailed               = "UPDATE_HELPER_FAILED"
	CodeUpdateStateInvalid               = "UPDATE_STATE_INVALID"
	CodeSchemaNotFound                   = "SCHEMA_NOT_FOUND"
	CodeSchemaInvalid                    = "SCHEMA_INVALID"
	CodeSchemaMetadataMismatch           = "SCHEMA_METADATA_MISMATCH"
	CodeInvalidInputJSON                 = "INVALID_INPUT_JSON"
	CodeValidationError                  = "VALIDATION_ERROR"
	CodeCommandTypeMismatch              = "COMMAND_TYPE_MISMATCH"
	CodeMissingRequiredField             = "MISSING_REQUIRED_FIELD"
	CodeUnknownField                     = "UNKNOWN_FIELD"
	CodeInvalidFieldType                 = "INVALID_FIELD_TYPE"
	CodeInvalidEnumValue                 = "INVALID_ENUM_VALUE"
	CodeInvalidRange                     = "INVALID_RANGE"
	CodeInvalidFile                      = "INVALID_FILE"
	CodeAssetURLNotFound                 = "ASSET_URL_NOT_FOUND"
	CodeAssetMatchAmbiguous              = "ASSET_MATCH_AMBIGUOUS"
	CodeUploadFailed                     = "UPLOAD_FAILED"
	CodeDownloadFailed                   = "DOWNLOAD_FAILED"
	CodeArtifactDownloadFailed           = "ARTIFACT_DOWNLOAD_FAILED"
	CodeOutputPathAmbiguous              = "OUTPUT_PATH_AMBIGUOUS"
	CodeOutputPathExists                 = "OUTPUT_PATH_EXISTS"
	CodeAssetDBOpenFailed                = "ASSET_DB_OPEN_FAILED"
	CodeAssetDBWriteFailed               = "ASSET_DB_WRITE_FAILED"
	CodeTaskTimeout                      = "TASK_TIMEOUT"
	CodeTaskFailed                       = "TASK_FAILED"
	CodeTaskCancelled                    = "TASK_CANCELLED"
	CodeTaskExpired                      = "TASK_EXPIRED"
	CodeTaskStatusInvalid                = "TASK_STATUS_INVALID"
)

const (
	MessageMissingCommand              = "missing command"
	MessageOutputWriteVersionFailed    = "failed to write version output"
	MessageInitNotImplemented          = "init command is not implemented yet"
	MessageUpdateNotImplemented        = "update command is not implemented yet"
	MessageAuthNotImplemented          = "auth command is not implemented yet"
	MessageAuthLoginNotImplemented     = "auth login command is not implemented yet"
	MessageAuthLogoutNotImplemented    = "auth logout command is not implemented yet"
	MessageAuthStatusNotImplemented    = "auth status command is not implemented yet"
	MessageTypesNotImplemented         = "missing types subcommand"
	MessageTypesListNotImplemented     = "types list command is not implemented yet"
	MessageTypesInspectNotImplemented  = "types inspect command is not implemented yet"
	MessageTaskNotImplemented          = "task command is not implemented yet"
	MessageTaskStatusNotImplemented    = "task status command is not implemented yet"
	MessageTaskWaitNotImplemented      = "task wait command is not implemented yet"
	MessageTaskCancelNotImplemented    = "task cancel command is not implemented yet"
	MessageGenerateImageNotImplemented = "generateImage command is not implemented yet"
	MessageGenerateVoiceNotImplemented = "generateVoice command is not implemented yet"
	MessageGenerateVideoNotImplemented = "generateVideo command is not implemented yet"
)
